server:
  port: 8080

springdoc:
  swagger-ui:
    path: /timesheets-documentation
  api-docs:
    path: /timesheets-api-documentation

spring:
  application:
    name: timesheet-rest #+ключ в эврике
  datasource:
    url: jdbc:postgresql://localhost:5432/timesheets
#    url: jdbc:h2:mem:test
    username: sa
    password: sa
    driver-class-name: org.postgresql.Driver
#    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true