server:
  port: 8080
#это пришло из модуля логгирования, в частности, аспект Logging
# указывать можно уровни, описанные внутри аспекта
application:
  recover:
    enabled: true
    no-recover-for: #НЕ нужно обрабатывать
      - java.lang.ClassNotFoundException
      - java.lang.ArithmeticException
  logging:
    level: WARN
    enable-aspect: true #вкл или выклю всю систему в целом

springdoc:
  swagger-ui:
    path: /timesheets-documentation
  api-docs:
    path: /timesheets-api-documentation

spring:
  application:
    name: timesheet-rest #+ключ в эврике
  datasource:
    url: jdbc:postgresql://localhost:5432/timesheets
#    url: jdbc:h2:mem:test
    username: sa
    password: sa
    driver-class-name: org.postgresql.Driver
#    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true